name: Test Coverage

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # supported python versions can be found here
        # https://github.com/actions/python-versions/releases
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, 3.10.0-alpha.5]
    steps:
      - uses: actions/checkout@master
      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U wheel
          pip install -r requirements.txt
          pip install -U pytest coverage
          pip install .
      - name: Run mypy
        if: "matrix.python-version != '2.7' && matrix.python-version != 'pypy2'"
        run: |
            pip install -U mypy
            mypy -p plyse --ignore-missing-imports
      - name: Run tests & coverage
        run: |
          coverage erase
          coverage run -m pytest -v --color=yes
          coverage report -m
